export const login = '/login'
export const logout = '/logout'
export const user = '/user'
export const pvc = "/pvc?page=1&perPage=127";
export const pvcCount = "/pvc-count";
export const lga = "/pvc/statistics?type=lga";
export const occupation = "/pvc/statistics?type=occupation";
export const age = "/pvc/age_statistics";
export const reach = "/pvc/count/gender_lga";